### ISSUE TITLE
Inspirations

### ISSUE THREAD

**Issue by krischer** [SalvusHub/salvus#2]
Hey guys,

I found this cool generic finite element package that I think can serve as some inspiration for us: http://montjoie.gforge.inria.fr/index.php

It can solve a number of equations and seems to be very general. They have a variety of different elements with different basis functions, CG & DG support, a number of time schemes (implicit and explicit), hybrid mesh support, various boundary conditions, and a lot more. Importantly they also have quite a nice documentation.

They solved a number of problems we also want to solve and thus we can probably learn from them in terms of code architecture and how to structure things so we don't end up in some kind of dead end somewhere down the road.

We can probably not directly use it as I don't think it parallelizes with MPI.

On that note: why can't we use one of the existing finite element packages, e.g.

* https://www.dune-project.org/
* https://www.dealii.org/

You all know more about numerics than me so some comments would be nice!

**Comment by michael-afanasiev** [comment]
I'll throw my two cents in. I looked at dealii, libmesh, and fenics before I started (never dune tho). The problem I had with all three was weight and level of generalization. I realized that, after writing some spectral stuff in python, that the actual engine of the method wasn't that complicated. After I scaled it up in c++ however, I realized that pretty much all the difficulty was in annoying things (node mappings, parallelization, oreintation, etc.) From what I saw, PETSc was the best library that would deal with only those annoying things, leaving us to design the other parts ourselves. That being said, it actually does have most of the functionality the other libraries have (see the documentation for DMPLEX if you're brave), but I doubt using these functions would be much easier than just dealing with our own.

In the end, there's only about 10 Petsc functions that are actually used, and very sparingly. Seems like a nice mix of control and re-use.

**Comment by michael-afanasiev** [comment]
Just another comment on generality. In the other FEM libraries, it seems like we'd be inheriting an ecosystem, and then trimming out those parts we don't need. Basically, taking them from very general concepts to something more specific. With PETSc, the practice is the opposite. It's quite low level, and as such there's no real ecosystem to inherit... we just build what we need over some bare scaffolding. While I do see what we're doing as something general, I still imagine it to be focused on problems related specifically to seismology. If this is the focus, I think it's better to build a table from prefab 2x4s, rather than try and repurpose a bookshelf. If you know what I mean.

**Comment by krischer** [comment]
That sounds very reasonable. Thanks for sharing!
